version: '3'

services:
  app:
    image: matcom/dashboard:latest
    build: .
    user: "1000"
    ports:
      - "8501:8501"
    volumes:
      - ".:/src"
    working_dir: "/src"
    command: [ "streamlit", "run", "dashboard/⭐_dashboard.py" ]
