version: '3'

services:
  app:
    image: matcom/dashboard:latest
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ".:/src"
    command: [ "streamlit", "run", "dashboard/dashboard.py" ]
